name: ci
on:
  push:
    branches:
      - master
      - sequential-ci

  pull_request:
    branches:
      - master

  workflow_dispatch:

jobs:
  default:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Setup nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build
        run: nix develop .#with-ghc -c bash -c ".github/scripts/build_default.sh"

  sequential:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Setup nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build
        run: nix develop .#with-ghc -c bash -c ".github/scripts/build_sequential.sh"

  lint:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/run-ormolu@v16
        with:
          pattern: "./sequential/**/*.hs"
