name: ci
on:
  push:
    branches:
      - main
      - update-sequential-ci
  workflow_dispatch:
jobs:
  nix:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - uses: haskell-actions/setup@v2
        with:
          cabal-version: "3.12.1.0"
          ghc-version: "9.8.2"

      - name: Setup nix
        uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Compile
        run: nix develop .#ci -c bash -c ".github/build.sh"
