name: stable
on:
  push:
    branches:
      - master
      - snapshot-url

  pull_request:
    branches:
      - master

  schedule:
    # Once a week.
    #
    # https://crontab.guru
    - cron: '0 0 * * 0'

  workflow_dispatch:
jobs:
  trigger-build:
    uses: ./.github/workflows/runner.yaml
    with:
      snapshot: 'nightly-2026-08-30'
